version: '3'

services:
  postgres:
    image: postgres:11.3-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=my-secret-pw
      - POSTGRES_USER=liferay
      - POSTGRES_DB=lportal
    expose: 
      - 5432
    volumes:
      - $PWD/data/postgres:/var/lib/postgresql/data
    networks:
      - database
  ldap:
    image: osixia/openldap:1.2.4
    container_name: ldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    stdin_open: true
    volumes:
      - $PWD/data/ldap/database:/var/lib/ldap
      - $PWD/data/ldap/config:/etc/ldap/slapd.d
    domainname: "example.org"
    expose:
      - 389
      - 636
    networks:
      - database
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8090:80"
    networks:
      - database
      - default
  liferay:
    image: mdelapenya/liferay-portal:7.1.2-ga3
    container_name: liferay
    depends_on: 
      - postgres
    ports:
      - 8080:8080
      - 9000:9000
      - 11311:11311
    volumes:
      - $PWD/data/liferay:/storage
      - $PWD/data/setup:/tmp/liferay
    networks:
      - database
      - default  
networks:
  database:
    internal: true
  default:
    
